# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Network Architecture Lab
email: info@networkarchitecturelab.org
description: > # this means to ignore newlines until "baseurl:"
  The Network Architecture Lab is an experimental think-tank based in the New York City area investigating the impact of digital technology, telecommunications and changing sociocultural condition on architecture and society through research, publications and exhibitions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kazys

# Build settings
markdown: kramdown
